### ISSUE TITLE
segfault when pressing f1

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/growlight#102]
Debian bug #974888 reports a reliable segfault when pressing F1. This is pretty embarrassing, so let's get it knocked out ASAP.

**Comment by dankamongmen** [comment]
I think this is all coming from #99, where we moved away from known-good recursive locks. I'm gonna check -- I can readily reproduce this.

**Comment by dankamongmen** [comment]
Ahhh yeah, this appears to have always been broken for a file larger than the page size. Crikey!

**Comment by dankamongmen** [comment]
F1 now loads the help menu, though I couldn't reproduce this crash reported in the DBTS. We *were*, however, seeing crashes due to #103, which might be the problem he was running into (hopefully?).

**Comment by xtaran** [comment]
Well, yes, f3261dd did indeed fix it for pressing `F1`, but the problem persists with pressing `F2` to `F12` for me. See [my reply on the Debian bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=974888#25) for details. So I guess this is a "reopen". :-/

**Comment by dankamongmen** [comment]
Indeed it is. @xtaran provided one of the all-time great bug reports over in DBTS, and I intend to chase down the rest of the issues mentioned there.

I've fixed up your segfault on shutdown in #106 -- I'm pretty sure it'll handle that issue.

Actually, I'm going to close this back up, and make new issues for tracking the rest of your reported woes. Thank you **so much** for taking a patient look at growlight! I completely replaced its UI backend earlier this year (NCURSES -> notcurses) over the course of two days, and a number of things are shaking out.

**Comment by xtaran** [comment]
> I completely replaced its UI backend earlier this year (NCURSES -> notcurses) over the course of two days, and a number of things are shaking out.

Ah, this explains while the UI of a years-old tool made a rather rough impression. Thanks for sharing that detail!
